apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: menaangularappkubernetes 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: menaangularappkubernetes 
    spec:
      containers:
        - name: menaangularappkubernetes 
          image: jayaksacr.azurecr.io/menaangularappkubernetes
          ports:
          - containerPort: 80